[package]
name = "TradeAssistant"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "_"
trade_registry_addr = "_"
price_alert_addr = "_"
user_portfolio_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }

[dev-dependencies]
